---
# tasks file for jackett
- name: Add group for jackett
  group:
    name: jackett
    system: yes
- name: Add user for jackett
  user:
    name: jackett
    group: jackett
    system: yes
- name: Create a directory if it does not exist
  file:
    path: /opt/Jackett
    state: directory
    mode: '0755'
    owner: jackett
    group: jackett
- name: Download Jackett binaries
  unarchive:
    src: https://github.com/Jackett/Jackett/releases/download/v0.16.616/Jackett.Binaries.LinuxAMDx64.tar.gz
    dest: /opt/Jackett
    remote_src: yes
    owner: jackett
    group: jackett
    extra_opts:
      - '--strip-components=1'
- name: Install jackett service
  command: /opt/Jackett/install_service_systemd.sh