---
# tasks file for nordvpn
- name: Check if nordvpn is installed
  command: dpkg-query -W nordvpn
  register: nordvpn_check_deb
  failed_when: nordvpn_check_deb.rc > 1
  changed_when: nordvpn_check_deb.rc == 1
  tags:
    - nordvpn  
- name: Install nordvpn repo
  apt: deb=https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb
  become: true
  when: nordvpn_check_deb.rc == 1
  tags:
    - nordvpn 
- name: Install nordvpn
  apt: name=nordvpn update_cache=yes
  become: true
  when: nordvpn_check_deb.rc == 1
  tags:
    - nordvpn 

- name: Check if already logged into nordvpn
  shell: nordvpn account | grep {{ nordvpn_user|quote }}
  register: nordvpn_check_account
  failed_when: nordvpn_check_account.rc > 1
  changed_when: nordvpn_check_account.rc == 1
  tags:
    - nordvpn 
- name: Login to nordvpn
  command: nordvpn login -u {{ nordvpn_user|quote }} -p {{ nordvpn_pass|quote }}
  when: nordvpn_check_account.rc == 1
  tags:
    - nordvpn 

- name: Whitelist local network
  command: nordvpn whitelist add subnet {{ nordvpn_lan_cidr|quote }}
  tags:
    - nordvpn 
- name: Whitelist OpenDNS
  command: nordvpn whitelist add subnet 208.67.222.222/32
  tags:
    - nordvpn 

- name: Connect nordvpn
  command: nordvpn connect {{ nordvpn_server|quote }}
  tags:
    - nordvpn 
- name: Enable autoconnect
  command: nordvpn set autoconnect on
  tags:
    - nordvpn 