---
# This playbook deploys the whole application stack in this site.

- name: configure moviebox server
  hosts: moviebox
  become: true

  pre_tasks:
    - name: 'Check mandatory variables are defined'
      assert:
        that:
          - samba_user_password is defined
    - name: Ensure package database is up-to-date
      apt:
        update-cache: true
      failed_when: false
      changed_when: false
      when: ansible_os_family == 'Debian'
    - name: Create users
      user:
        name: '{{ item }}'
        groups: users
        append: true
      with_items:
        - tv

  vars:
    samba_log: /var/log/samba.log
    samba_log_size: 60000
    samba_log_level: '3 passdb:5 auth:10 winbind:2 '

    samba_users:
      - name: tv
        password: '{{ samba_user_password }}'

    samba_shares_root: /mnt/hdd1/shares
    samba_shares:
      - name: Movies
        comment: 'Awesome Movies'
        public: 'yes'
        write_list: +users
        group: users
        browseable: 'yes'
      - name: 'TV-Series'
        comment: 'Awesome TV-Series'
        public: 'yes'
        write_list: +users
        group: users
        browseable: 'yes'

  roles:
    - {role: bertvv.samba}