---
# This playbook will install and configure Samba.

- name: Ensure Samba-related packages are installed.
  apt: 
    state: present
    name:
      - samba
      - samba-common

- name: Ensure Samba is running and set to start on boot.
  service: "name=smbd state=started enabled=yes"